cwlVersion: v1.2
class: CommandLineTool
label: Predict
$namespaces:
  sbg: https://sevenbridges.com

requirements:
- class: ShellCommandRequirement
- class: DockerRequirement
  dockerPull: images.sb.biodatacatalyst.nhlbi.nih.gov/e.esquinca/ind_level_predixcan:dev
- class: InlineJavascriptRequirement

inputs:
- id: model_db_path
  doc: Path to a SQlite file containing prediction models.
  type: File
  inputBinding:
    prefix: --model_db_path
    position: 0
    shellQuote: false
- id: vcf_genotypes
  doc: Pattern of vcf genotype files.
  type: File[]?
  inputBinding:
    prefix: --vcf_genotypes
    position: 0
    shellQuote: false
- id: vcf_mode
  doc: |-
    -"genotyped" is meant for phased, genotyped vcfs that contain counts of each allele at each chromosome pair.
    -"imputed" will load DS field as dosage. This is meant to work with imputed vcfs as generated by the Michigan Imputation Server.
  type: string?
  inputBinding:
    prefix: --vcf_mode
    position: 0
    shellQuote: false
- id: prediction_summary_output
  doc: |-
    A separate file that will contain some additional information on the predictions (such as number of snps in the gene's models, number of snps used, etc).
  type: string
  inputBinding:
    prefix: --prediction_summary_output
    position: 0
    shellQuote: false
- id: prediction_output
  doc: Specify output (and output type) of predicted expression matrix
  type: string
  inputBinding:
    prefix: --prediction_output
    position: 0
    shellQuote: false
- id: verbosity
  doc: |-
    This value will change the amount of detail displayed. Default value is 9. Change to a smaller number to receive more detail about prediction.
  type: int?
  default: 9
  inputBinding:
    prefix: --verbosity
    position: 0
    shellQuote: false
- id: model_db_snp_key
  doc: |-
    Optional. If provided, will load variant ids from an alternative column in the db. By default, PrediXcan uses rsids, and this works with Elastic Net models. For the more sophisticated MASHR models, --model_db_snp_key varID must be specified with this argument.
  type: string?
  inputBinding:
    prefix: --model_db_snp_key
    position: 0
    shellQuote: false
- id: on_the_fly_mapping
  doc: |-
    Optional. Specify a pattern to build a variant id from genotype variant properties. e.g. --on_the_fly_mapping METADATA "chr{}_{}_{}_{}_b38" will take the genotype variant's chromosome, position, alleles to build a variant id like chr1_123_A_G_b38. This will use the genotype properties, or if liftover is specified, the lifted coordinates.
  type: string?
  inputBinding:
    position: 0
    shellQuote: false
- id: text_genotypes
  doc: |-
    Use the text format as specified by: https://github.com/hakyimlab/MetaXcan/wiki/Individual-level-PrediXcan:-introduction,-tutorials-and-manual
  type: File?
  inputBinding:
    prefix: --text_genotypes
    position: 0
    shellQuote: false
- id: text_sample_ids
  doc: |-
    A file specifying samples. If specified alongside bgen or vcf, will use the file's IDs instead of the ones in the vcf or bgen.
  type: File?
  inputBinding:
    prefix: --text_sample_ids
    position: 0
    shellQuote: false

outputs:
- id: prediction
  type: File?
  outputBinding:
    glob: $(inputs.prediction_output)
- id: summary
  type: File?
  outputBinding:
    glob: $(inputs.prediction_summary_output)

baseCommand:
- python3
- /opt/MetaXcan/software/Predict.py
arguments:
- prefix: ''
  position: 9999
  valueFrom: --throw
  separate: false
  shellQuote: false

hints:
- class: sbg:SaveLogs
  value: standard.out
- class: sbg:SaveLogs
  value: '*.sh'
- class: sbg:SaveLogs
  value: '*.py'
id: e.esquinca/individual-level-predixcan-development/predict/27
sbg:appVersion:
- v1.2
sbg:content_hash: a290e9b15e12cb740979f9aec4d820aa48f2fc40b46afc70f3024339432a5c339
sbg:contributors:
- e.esquinca
sbg:createdBy: e.esquinca
sbg:createdOn: 1623963857
sbg:id: e.esquinca/individual-level-predixcan-development/predict/27
sbg:image_url:
sbg:latestRevision: 27
sbg:modifiedBy: e.esquinca
sbg:modifiedOn: 1630283684
sbg:project: e.esquinca/individual-level-predixcan-development
sbg:projectName: 'BUILD: Individual Level PrediXcan Development'
sbg:publisher: sbg
sbg:revision: 27
sbg:revisionNotes: updated descriptions
sbg:revisionsInfo:
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1623963857
  sbg:revision: 0
  sbg:revisionNotes:
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1623964298
  sbg:revision: 1
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1623965791
  sbg:revision: 2
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1623975522
  sbg:revision: 3
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624395875
  sbg:revision: 4
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624398812
  sbg:revision: 5
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624473667
  sbg:revision: 6
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624474304
  sbg:revision: 7
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624484331
  sbg:revision: 8
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624484486
  sbg:revision: 9
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624487042
  sbg:revision: 10
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624487314
  sbg:revision: 11
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624561938
  sbg:revision: 12
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624562453
  sbg:revision: 13
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624567552
  sbg:revision: 14
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1624567938
  sbg:revision: 15
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1625614955
  sbg:revision: 16
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1625617437
  sbg:revision: 17
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1625617458
  sbg:revision: 18
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1626120935
  sbg:revision: 19
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627073868
  sbg:revision: 20
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627589721
  sbg:revision: 21
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627589974
  sbg:revision: 22
  sbg:revisionNotes: separate output globs
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627590577
  sbg:revision: 23
  sbg:revisionNotes: ''
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627600358
  sbg:revision: 24
  sbg:revisionNotes: temp disable on the fly
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627600880
  sbg:revision: 25
  sbg:revisionNotes: temp disable of on the fly
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1627601574
  sbg:revision: 26
  sbg:revisionNotes: put on the fly back in
- sbg:modifiedBy: e.esquinca
  sbg:modifiedOn: 1630283684
  sbg:revision: 27
  sbg:revisionNotes: updated descriptions
sbg:sbgMaintained: false
sbg:validationErrors: []
